info:
  name: Swagger Health check (200)
  type: http
  seq: 1

http:
  method: GET
  url: https://petstore.swagger.io/v2/swagger.json
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        test("Status is 200", function() {
          expect(res.getStatus()).to.equal(200);
        });

        test("Swagger version present", function() {
          const data = res.getBody();
          expect(data.swagger).to.equal("2.0");
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
